name: PR check
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

  tests:
    name: Run test
    runs-on: ubuntu-latest
    needs: [build]

    services:
      devnet:
        image: janek2601/starknet-devnet-patched
        ports:
          - 5050:5050
    env:
      TEST_PROVIDER_BASE_URL: http://127.0.0.1:5050/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: npm test
